### ISSUE TITLE
Help Panel Content

### ISSUE THREAD

**Issue by rmroot** [NREL/NEB-Tool#228] opened 2024-09-10 18:50 UTC
With the help panel added (#134) we will need the content of the components properly filled out. I'll provide a checklist of the pages needing help text:

- [ ] Company General Details
- [ ] Stakeholder Contacts
- [ ] Select KPIs
- [ ] KPI Details
- [ ] Facility General Details
- [ ] Industrial system Inventory
- [ ] End Use Inventory
- [ ] Pre-Assessments page
- [ ] Review Pre-visit
- [ ] Manage Assessments
- [ ] Assessment Details
- [ ] Assessment Energy Efficiency Opportunities
- [ ] Assessment NEBs
- [ ] Assessment Results
- [ ] Data Evaluation Follow-up
- [ ] Assessment Report
- [ ] Rollup Report

We could potentially break this up into individual issues or just use this checklist.

**Comment by koay9f** [comment] 2024-11-25 21:04
**Company Details:**
Provide details about the company.
Company Name is the only required field, all others are optional.
Energy Results Unit sets the roll up unit for combining energy results from different utilities. It defaults to MMBtu.

**Stakeholder Contacts:**
Enter stakeholder details of people that will be invested in the companies quest to find Non-Energy Benefits!
These are people who could help gather data regarding Key Performance Indicators and Metrics (KPIs and KPMs), energy use, or would be interested in results.
This information can be used to help get in contact with these individuals later.
Stakeholders can also be attached to KPIs, NEBs, Industrial Systems, and End Uses.

I think KPIs and KPMs pages are good for now.

Facility Details: 
Provide details about the facility.
Facility Name is the only required field, all others are optional. Tracked Utilities is highly recommended.
Tracked Utilities is the place to enter annual data regarding different utilities (electricity, natural gas, water, etc.)
Focus on utilities connected to the system being assessed (electricity for pumps, fans, motors, etc.; natural gas for heating, steam, etc.).
The "Compressed Air" and "Steam" utilities are used when compressed air and steam cross the facility fence and are not produced on-site.

**Industrial System Inventory**
Add equipment to the "Industrial System Inventory" for the selected facility.
This inventory focuses on equipment related to assessments that are being conducted: larger motor driven systems (pumps, fans, compressors), process heating equipment, steam equipment. Systems like lighting equipment, HVAC systems, and mobile equipment can also be tracked.
Setting the "Industrial System" sets the energy-related fields and Utility Type sets the units available for Total Size.

Enter **nameplate** data for Total Size to begin estimating the energy used by the system. 
Operating Hours refers to the hours the equipment (not the entire facility) is operating
Load Factor refers to the fraction of the nameplate size power that is being used.
Efficiency refers to the energy efficiency of the equipment.
Number of Equipment can be utilized if multiple equipment is about the same size
Notes can be used to help start to take notes about the equipment and how it connects to end users and potential NEBs.

Click the **Stakeholders** button to connect stakeholders to the equipment.

**End Use Inventory**
Add end uses to the inventory for the selected facility.

Name and make notes about end uses of outputs of the Industrial Systems. 

Click the **Stakeholders** button to connect stakeholders to the equipment.

**Pre-Assessment**

Enter details about the assessments that are going to be conducted at the selected facility.

Select the start date of the assessments. This will be used to group together assessments if you have multiple visits to the selected facility.

Details about the results of the assessment can also be entered during the data collection phase. In the pre-assessment, this is a high level estimate of the annual energy used by the system being assessed. It will be used to estimate the relative change in utility use caused by implementing the opportunities found in the assessment (percent savings). 
If the assessment is a Treasure Hunt, please put in the facility-level annual use for any utility where savings may be found.  Units can be set independently. 


**Manage Assessments** - this is good

**Assessment Details**
Provide details for this assessment with regards to the equipment and utility types .

Some details may have been added during the pre-assessment phase but can be modified here.
In the assessment, this should be a good estimate of the annual energy used by the system being assessed. It will be used to estimate the relative change in utility use caused by implementing the opportunities found in the assessment (percent savings). 
If the assessment is a Treasure Hunt, please put in the facility-level annual use for any utility where savings may be found.  Units can be set independently. 

Implementation costs and the results of the energy and cost savings can be added at an assessment level (here) or at an opportunity level under the "Energy Efficiency Opportunities" tab. They should be added here if they cannot be disaggregated from each other (the opportunities build upon each other), but otherwise they will be best added in each opportunity. 

I think the other pages are okay for now...

**Closed as completed** 2024-12-02 16:58 UTC
Labels: Help Text
