### ISSUE TITLE
Data validation company.team-details/contact

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#115] opened 2024-06-06 21:51 UTC

**Comment by RLiNREL** [comment] 2024-06-13 16:43
Feedback from 06/13 meeting:
- Add * next to Name to indicate required field
- Separate name to first and last names for sorting by last name
- Change error message (red) to warning (yellow) for the input fields, phone and email, except Name
- Allow to next step even if the phone and email inputs are invalid (use only the company name as road blocker)
- Add a phone extension on the right as optional part of phone number
- UX: Disable warning for first time type-in, but enable when focus is lost.

**Comment by rmroot** [comment] 2024-07-16 13:12
A couple quick updates I noticed since merging these changes into the my own work:
- I think we want to save change on (input) for everything but dropdowns and checkboxes/radios that use (change) instead of (blur).
- I'm not sure why we have the comma being added between first and last name.
- There is an `if` statement that is incorrect. The block for `if(names.length < 1)` should be `if(names.length == 1)` I just had "Mark Root" and it threw errors. I'm a little worried that splitting the names is going to cause more headaches then we want but we can keep it for now
<img width="464" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTNpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfa1268313df3e587554cc9496678ae6847da52d/Screenshot%202024-07-16%20at%208.11.12%E2%80%AFAM.png" alt="Screenshot 2024-07-16 at 8.11.12 AM.png" />

**Comment by RLiNREL** [comment] 2024-07-16 15:27
Thanks, @rmroot for pointing it out. I pushed a couple of new commits.
1. (blur) is replaced by (input)
2. The comma is used to distinguish first and last names when the full name is extracted from idb, especially if the first name contains two words separated by spaces. It may be visually helpful for the user to see the first and last names separated in the upper left corner of the accordion. It is a temporary splitter for now.
3. Thanks for spotting it! Fixed.

I agree that we should have separate first and last names properties for the contact later.
A new issue was added #158

**Comment by ghost** [comment] 2024-07-25 17:16
Before closing this, I think the comma should be rejected as an input for the name fields. You can produce weird bugs by entering commas. For example:

Using v0.0.1-alpha-3483233

Steps to reproduce:
- Open a new wizard.
- Navigate to Team details page.
- Add a new team member.
- Type in "First, First" as first name
- Type in "Last, Last" as last name
- Navigate away from the page
- Navigate back to the Team Details page.

Expected behavior:
- Commas in the name are rejected (at least until #158 is implemented)

Observed behavior:
- The text fields have changed. The "First" field is now "First" and the "Last" field is also "First". Interestingly, the full name printed in the accordion header sill reads "First, First, Last, Last"

**Comment by RLiNREL** [comment] 2024-07-25 19:08
@jperrsau-at-nrel  good points. The current implementation, splits the full name by comma, and take the first two entries as first and last names. That's why you see the behavior that the First and First are extracted as first and last names.

I think it may be better to implement #158 now instead of preventing commas from input, as we need some inputs around some discussion points from other team members to move forward. I will go ahead and move #158 to in progress. You could close this #115 issue or keep it open until #158 is done. Thanks

**Closed as completed** 2024-10-29 14:45 UTC
